[package]
name = "ParthenonPals"
version = "0.0.1"
authors = []

[addresses]
ParthenonPals = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
